dog_flask/models.py
from datetime import datetime

from dog_flask.extensions import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), nullable=False)
    subtitle = db.Column(db.String(50))
    author = db.Column(db.String(50))
    main_img = db.Column(db.String(50))
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"{self.id}, {self.title}, {self.subtitle}, {self.author}, {self.content}"

dog_flask/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = StringField("Titulek", validators=[DataRequired(), Length(min=5, max=50)])
    subtitle = StringField("Podtitulek")
    content = TextAreaField("Obsah")
    author = StringField("Autor")

    submit = SubmitField("Uložit")

dog_flask/__init__.py
from flask import Flask
from flask_admin.contrib.sqla import ModelView

from dog_flask.extensions import db, migrate, admin
from dog_flask.routes import main
from dog_flask.models import Post


def create_app(config_file="settings.py"):
    app = Flask(__name__)
    app.config.from_pyfile(config_file)

    db.init_app(app)
    migrate.init_app(app, db)
    admin.init_app(app)
    admin.add_view(ModelView(Post, db.session))
    app.register_blueprint(main)

    return app

dog_flask/routes.py
from flask import Blueprint, render_template, redirect, url_for

from dog_flask.extensions import db
from dog_flask.forms import PostForm
from dog_flask.models import Post

main = Blueprint("main", __name__)


@main.route("/")
def index():
    posts = Post.query.order_by(Post.date_posted.desc()).all()

    return render_template("index.html", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html")


@main.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get(post_id)
    return render_template("post.html", post=post)


@main.route("/contact")
def contact():
    return render_template("contact.html")


@main.route("/add_post", methods=["GET", "POST"])
def add_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post(title=form.title.data, subtitle=form.subtitle.data, content=form.content.data,
                        author=form.author.data)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for("main.index"))
    return render_template("add_post.html", form=form)

dog_flask/templates/about.html
{% extends "layout.html" %}

{% block header %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/about-bg.jpg') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur
                    voluptates
                    odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus
                    consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque
                    architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum
                    in
                    officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid
                    ex
                    itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit
                    tempora!</p>
            </div>
        </div>
    </div>
{% endblock content %}

dog_flask/templates/add_post.html
{% extends "layout.html" %}

{% block header %}
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/stenata.gif') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>Přidat Článek</h1>
                        <span class="subheading">Tady můžeš přidat článek</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p>Vyplň a ulož článek na stránky</p>

                {#                <form name="sentMessage" id="contactForm" method="post">#}
                <form method="post" action="">
                    {{ form.hidden_tag() }}
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls">
                            {{ form.title.label }}
                            {% if form.title.errors %}
                                {{ form.title(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in  form.title.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.title(class="form-control", placeholder="Titulek") }}
                            {% endif %}
                        </div>
                        <div class="form-group floating-label-form-group controls">
                            {{ form.subtitle.label }}
                            {% if form.subtitle.errors %}
                                {{ form.subtitle(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in  form.subtitle.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.subtitle(class="form-control", placeholder="Podtitulek") }}
                            {% endif %}
                        </div>
                        <div class="form-group floating-label-form-group controls">
                            {{ form.author.label }}
                            {% if form.author.errors %}
                                {{ form.author(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in  form.author.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.author(class="form-control", placeholder="Autor") }}
                            {% endif %}
                        </div>
                        <div class="form-group floating-label-form-group controls">
                            {{ form.content.label }}
                            {% if form.content.errors %}
                                {{ form.content(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in  form.content.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.content(class="form-control", placeholder="Obsah") }}
                            {% endif %}
                        </div>

                    </div>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock content %}

dog_flask/templates/contact.html
{% extends "layout.html" %}

{% block header %}
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/contact-bg.jpg') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <span class="subheading">Have questions? I have answers.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon
                    as
                    possible!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required
                                   data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required
                                   data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required
                                   data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required
                                      data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

dog_flask/templates/index.html
{% extends "layout.html" %}

{% block header %}
    <header class="masthead"
            {#            style="background-image: url({{ url_for('static', filename='home-bg.jpg') }})">#}
            style="background-image: url({{ url_for('static', filename='img/hundarna1.jpg') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Hezky Cesky</h1>
                        <span class="subheading">Nase chovatelska stanice</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for post in posts %}
                    <div class="post-preview">
                        <a href="{{ url_for('main.post', post_id=post.id) }}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                {{ post.subtitle }}
                            </h3>
                        </a>
                        <p class="post-meta">Od
                            <a href="#">{{ post.author }}</a>
                            - {{ post.date_posted }}</p>
                    </div>
                    <hr>
                {% endfor %}
                <!-- Pager -->
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

dog_flask/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% if title %}
        <title>Hezky Český - {{ title }}</title>
    {% else %}
        <title>Hezky Český</title>
    {% endif %}

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('static', filename='css/all.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/clean-blog.min.css') }}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Hezky Český</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Domů</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">O nás</a>
                </li>
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link" href="{{ url_for('post') }}">Sample Post</a>#}
                {#                </li>#}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.contact') }}">Kontakt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.add_post') }}">Přidat článek</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block header %}{% endblock header %}
{% block content %}{% endblock content %}
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

</body>

</html>

dog_flask/templates/post.html
{% extends "layout.html" %}

{% block header %}
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/post-bg.jpg') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1>{{ post.title }}</h1>
                        <h2 class="subheading">{{ post.subtitle }}</h2>
                        <span class="meta">Od {{ post.author }} - {{ post.date_posted }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    {{ post.content | safe }}

                    {#                    <p>Never in all their history have men been able truly to conceive of the world as one: a single#}
                    {#                        sphere,#}
                    {#                        a globe, having the qualities of a globe, a round earth in which all the directions eventually#}
                    {#                        meet,#}
                    {#                        in which there is no center because every point, or none, is center — an equal earth which all#}
                    {#                        men#}
                    {#                        occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in#}
                    {#                        practice,#}
                    {#                        not in theory.</p>#}
                    {##}
                    {#                    <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no#}
                    {#                        turning back from science. The early warnings about technological dangers also come from#}
                    {#                        science.</p>#}
                    {##}
                    {#                    <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that#}
                    {#                        they#}
                    {#                        set eye on the earth.</p>#}
                    {##}
                    {#                    <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become#}
                    {#                        her#}
                    {#                        protectors rather than her violators. That's how I felt seeing the Earth for the first time. I#}
                    {#                        could#}
                    {#                        not help but love and cherish her.</p>#}
                    {##}
                    {#                    <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who#}
                    {#                        will, the experience most certainly changes your perspective. The things that we share in our#}
                    {#                        world#}
                    {#                        are far more valuable than those which divide us.</p>#}
                    {##}
                    {#                    <h2 class="section-heading">The Final Frontier</h2>#}
                    {##}
                    {#                    <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally,#}
                    {#                        it#}
                    {#                        is a task to occupy the generations. And no matter how much progress one makes, there is always#}
                    {#                        the#}
                    {#                        thrill of just beginning.</p>#}
                    {##}
                    {#                    <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally,#}
                    {#                        it#}
                    {#                        is a task to occupy the generations. And no matter how much progress one makes, there is always#}
                    {#                        the#}
                    {#                        thrill of just beginning.</p>#}
                    {##}
                    {#                    <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of#}
                    {#                        tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet#}
                    {#                        far#}
                    {#                        too little for the next ten.#}
                    {#                    </blockquote>#}
                    {##}
                    {#                    <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is#}
                    {#                        a#}
                    {#                        historical process which mankind is carrying out in accordance with the natural laws of human#}
                    {#                        development.</p>#}
                    {##}
                    {#                    <h2 class="section-heading">Reaching for the Stars</h2>#}
                    {##}
                    {#                    <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the#}
                    {#                        size#}
                    {#                        of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so#}
                    {#                        fragile, so delicate, that if you touched it with a finger it would crumble and fall apart.#}
                    {#                        Seeing#}
                    {#                        this has to change a man.</p>#}
                    {##}
                    {#                    <a href="#">#}
                    {#                        <img class="img-fluid" src="{{ url_for('static', filename='img/post-sample-image.jpg') }}"#}
                    {#                             alt="">#}
                    {#                    </a>#}
                    {#                    <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>#}
                    {##}
                    {#                    <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year#}
                    {#                        mission:#}
                    {#                        to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no#}
                    {#                        man#}
                    {#                        has gone before.</p>#}
                    {##}
                    {#                    <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a#}
                    {#                        fundamental#}
                    {#                        truth to our nature, Man must explore, and this is exploration at its greatest.</p>#}
                    {##}
                    {#                    <p>Placeholder text by#}
                    {#                        <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by#}
                    {#                        <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p>#}
                </div>
            </div>
        </div>
    </article>
{% endblock content %}

templates/index.html
{% extends "layout.html" %}

{% block header %}
    <header class="masthead"
            {#            style="background-image: url({{ url_for('static', filename='home-bg.jpg') }})">#}
            style="background-image: url({{ url_for('static', filename='img/hundarna1.jpg') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Hezky Cesky</h1>
                        <span class="subheading">Nase chovatelska stanice</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for post in posts %}
                    <div class="post-preview">
                        <a href="{{ url_for('post', post_id=post.id) }}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                {{ post.subtitle }}
                            </h3>
                        </a>
                        <p class="post-meta">Od
                            <a href="#">{{ post.author }}</a>
                            - {{ post.date_posted }}</p>
                    </div>
                    <hr>
                {% endfor %}
                <!-- Pager -->
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}